package GreenDaoDB;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import zj.health.health_v1.Model.CalendarDateListModel;
import zj.health.health_v1.Model.ConsultTimeModel;
import zj.health.health_v1.Model.DrugNameModel;
import zj.health.health_v1.Model.LiveMode;
import zj.health.health_v1.Model.MessageEntity;
import zj.health.health_v1.Model.QuestionModel;
import zj.health.health_v1.Model.ReportModel;
import zj.health.health_v1.Model.SportModes;
import zj.health.health_v1.Model.UserInfo;
import zj.health.health_v1.Model.Users;

import GreenDaoDB.CalendarDateListModelDao;
import GreenDaoDB.ConsultTimeModelDao;
import GreenDaoDB.DrugNameModelDao;
import GreenDaoDB.LiveModeDao;
import GreenDaoDB.MessageEntityDao;
import GreenDaoDB.QuestionModelDao;
import GreenDaoDB.ReportModelDao;
import GreenDaoDB.SportModesDao;
import GreenDaoDB.UserInfoDao;
import GreenDaoDB.UsersDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig calendarDateListModelDaoConfig;
    private final DaoConfig consultTimeModelDaoConfig;
    private final DaoConfig drugNameModelDaoConfig;
    private final DaoConfig liveModeDaoConfig;
    private final DaoConfig messageEntityDaoConfig;
    private final DaoConfig questionModelDaoConfig;
    private final DaoConfig reportModelDaoConfig;
    private final DaoConfig sportModesDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig usersDaoConfig;

    private final CalendarDateListModelDao calendarDateListModelDao;
    private final ConsultTimeModelDao consultTimeModelDao;
    private final DrugNameModelDao drugNameModelDao;
    private final LiveModeDao liveModeDao;
    private final MessageEntityDao messageEntityDao;
    private final QuestionModelDao questionModelDao;
    private final ReportModelDao reportModelDao;
    private final SportModesDao sportModesDao;
    private final UserInfoDao userInfoDao;
    private final UsersDao usersDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        calendarDateListModelDaoConfig = daoConfigMap.get(CalendarDateListModelDao.class).clone();
        calendarDateListModelDaoConfig.initIdentityScope(type);

        consultTimeModelDaoConfig = daoConfigMap.get(ConsultTimeModelDao.class).clone();
        consultTimeModelDaoConfig.initIdentityScope(type);

        drugNameModelDaoConfig = daoConfigMap.get(DrugNameModelDao.class).clone();
        drugNameModelDaoConfig.initIdentityScope(type);

        liveModeDaoConfig = daoConfigMap.get(LiveModeDao.class).clone();
        liveModeDaoConfig.initIdentityScope(type);

        messageEntityDaoConfig = daoConfigMap.get(MessageEntityDao.class).clone();
        messageEntityDaoConfig.initIdentityScope(type);

        questionModelDaoConfig = daoConfigMap.get(QuestionModelDao.class).clone();
        questionModelDaoConfig.initIdentityScope(type);

        reportModelDaoConfig = daoConfigMap.get(ReportModelDao.class).clone();
        reportModelDaoConfig.initIdentityScope(type);

        sportModesDaoConfig = daoConfigMap.get(SportModesDao.class).clone();
        sportModesDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        calendarDateListModelDao = new CalendarDateListModelDao(calendarDateListModelDaoConfig, this);
        consultTimeModelDao = new ConsultTimeModelDao(consultTimeModelDaoConfig, this);
        drugNameModelDao = new DrugNameModelDao(drugNameModelDaoConfig, this);
        liveModeDao = new LiveModeDao(liveModeDaoConfig, this);
        messageEntityDao = new MessageEntityDao(messageEntityDaoConfig, this);
        questionModelDao = new QuestionModelDao(questionModelDaoConfig, this);
        reportModelDao = new ReportModelDao(reportModelDaoConfig, this);
        sportModesDao = new SportModesDao(sportModesDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        usersDao = new UsersDao(usersDaoConfig, this);

        registerDao(CalendarDateListModel.class, calendarDateListModelDao);
        registerDao(ConsultTimeModel.class, consultTimeModelDao);
        registerDao(DrugNameModel.class, drugNameModelDao);
        registerDao(LiveMode.class, liveModeDao);
        registerDao(MessageEntity.class, messageEntityDao);
        registerDao(QuestionModel.class, questionModelDao);
        registerDao(ReportModel.class, reportModelDao);
        registerDao(SportModes.class, sportModesDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(Users.class, usersDao);
    }
    
    public void clear() {
        calendarDateListModelDaoConfig.clearIdentityScope();
        consultTimeModelDaoConfig.clearIdentityScope();
        drugNameModelDaoConfig.clearIdentityScope();
        liveModeDaoConfig.clearIdentityScope();
        messageEntityDaoConfig.clearIdentityScope();
        questionModelDaoConfig.clearIdentityScope();
        reportModelDaoConfig.clearIdentityScope();
        sportModesDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
        usersDaoConfig.clearIdentityScope();
    }

    public CalendarDateListModelDao getCalendarDateListModelDao() {
        return calendarDateListModelDao;
    }

    public ConsultTimeModelDao getConsultTimeModelDao() {
        return consultTimeModelDao;
    }

    public DrugNameModelDao getDrugNameModelDao() {
        return drugNameModelDao;
    }

    public LiveModeDao getLiveModeDao() {
        return liveModeDao;
    }

    public MessageEntityDao getMessageEntityDao() {
        return messageEntityDao;
    }

    public QuestionModelDao getQuestionModelDao() {
        return questionModelDao;
    }

    public ReportModelDao getReportModelDao() {
        return reportModelDao;
    }

    public SportModesDao getSportModesDao() {
        return sportModesDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

}
