package GreenDaoDB;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import zj.health.health_v1.Model.MessageEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MESSAGE_ENTITY".
*/
public class MessageEntityDao extends AbstractDao<MessageEntity, Long> {

    public static final String TABLENAME = "MESSAGE_ENTITY";

    /**
     * Properties of entity MessageEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property ConsultId = new Property(1, String.class, "ConsultId", false, "CONSULT_ID");
        public final static Property ConversationId = new Property(2, String.class, "ConversationId", false, "CONVERSATION_ID");
        public final static Property Frequency = new Property(3, int.class, "frequency", false, "FREQUENCY");
    }


    public MessageEntityDao(DaoConfig config) {
        super(config);
    }
    
    public MessageEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MESSAGE_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"CONSULT_ID\" TEXT," + // 1: ConsultId
                "\"CONVERSATION_ID\" TEXT," + // 2: ConversationId
                "\"FREQUENCY\" INTEGER NOT NULL );"); // 3: frequency
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MESSAGE_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MessageEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String ConsultId = entity.getConsultId();
        if (ConsultId != null) {
            stmt.bindString(2, ConsultId);
        }
 
        String ConversationId = entity.getConversationId();
        if (ConversationId != null) {
            stmt.bindString(3, ConversationId);
        }
        stmt.bindLong(4, entity.getFrequency());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MessageEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String ConsultId = entity.getConsultId();
        if (ConsultId != null) {
            stmt.bindString(2, ConsultId);
        }
 
        String ConversationId = entity.getConversationId();
        if (ConversationId != null) {
            stmt.bindString(3, ConversationId);
        }
        stmt.bindLong(4, entity.getFrequency());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public MessageEntity readEntity(Cursor cursor, int offset) {
        MessageEntity entity = new MessageEntity( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ConsultId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ConversationId
            cursor.getInt(offset + 3) // frequency
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MessageEntity entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setConsultId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setConversationId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFrequency(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MessageEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MessageEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MessageEntity entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
